from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage
import requests

from dotenv import load_dotenv
load_dotenv()
import os

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
# step1+++++++++++++++++++++++++++ tool creation +++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# tool creation
@tool
def multiply(a:int , b:int)->int:
    """This function takes two number a and b and return their product as output"""
    return a*b

# step2++++++++++++++++++++++++++++++++ tool binding ++++++++++++++++++++++++++++++++++++++++++++++++++++
# tool binding
model =ChatOpenAI()
llm_with_tool=model.bind_tools([multiply])



# Step3++++++++++++++++++++++++ tool calling ++++++++++++++++++++++
# here no tool calling will be done? because LLM knows it does not need tool to respod for this query.
result=llm_with_tool.invoke("hello how are you?")
# print(result)
# you will get response in result.content
# print(result.content)


#  here llm will call the tool and generate a structured output with function name and argument
result2=llm_with_tool.invoke("what is 10 multiply by 0?")
print(result2)
# you will not get any output here with result2.content
print(result2.content)

result3=llm_with_tool.invoke("what is 10 multiply by 0?").tool_calls[0]  #to see the structured output generated by LLM 
print(result3)


# Step4++++++++++++++++++++++++ tool execution ++++++++++++++++++++++

