from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage
import requests

from dotenv import load_dotenv
load_dotenv()
import os

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
# step1+++++++++++++++++++++++++++ tool creation +++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# tool creation
@tool
def multiply(a:int , b:int)->int:
    """This function takes two number a and b and return their product as output"""
    return a*b
# step2++++++++++++++++++++++++++++++++ tool binding ++++++++++++++++++++++++++++++++++++++++++++++++++++
# tool binding
model =ChatOpenAI()
llm_with_tool=model.bind_tools([multiply])

# Step3++++++++++++++++++++++++ tool calling ++++++++++++++++++++++
#  here llm will call the tool and generate a structured output with function name and argument
result2=llm_with_tool.invoke("what is 10 multiply by 12?")
print(result2)
# you will not get any output here with result2.content
print(result2.content)

result3=llm_with_tool.invoke("what is 10 multiply by 12?").tool_calls[0]["args"]  #to see the structured output generated by LLM 
print(result3)

result4=llm_with_tool.invoke("what is 10 multiply by 12?").tool_calls[0]
print(result4) # to see the first tool call , it is possible tool will have too many tools  , in some cases.

# Step4++++++++++++++++++++++++ tool execution ++++++++++++++++++++++
execution_res=multiply.invoke(result3)  #simple tool execution by only passing the argument
print(execution_res)

execution_res2=multiply.invoke({'name': 'multiply', 'args': {'a': 10, 'b': 12}, 'id': 'call_meYpxPgxveNir7YR2Q6jeuj6', 'type': 'tool_call'})  # tool execution , not only argument but tool tool call body paased
print(execution_res)

# Now last step5 to sent this all to LLM so that LLm can think and generate the final output.
query=HumanMessage("what is 10 multiply by 33?")
Messages=[query]
print(Messages)
# tool calling
AI_Suugested_Tool_Call_result=llm_with_tool.invoke(Messages)
Messages.append(AI_Suugested_Tool_Call_result)
print(Messages)
# tool execution ----> here also we will mot get LLM generated output , only output of tool function will be available. now those answer will be passed into LLM as conversation history , LLM will get the enitre context and generate a AI response.
toolResult=multiply.invoke(AI_Suugested_Tool_Call_result.tool_calls[0])
Messages.append(toolResult)
print(Messages)

# till here we were maintaining the history of our chat , and it is supposed to pass to LLM so that LLM can use them and understand and generate the output
gen_AI_output=llm_with_tool.invoke(Messages)
print(gen_AI_output)